version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: IA_DB
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
